### ISSUE TITLE
sack off git submodule for hugo templates

### ISSUE THREAD

**Issue by px3l** [strange-labs-uk/strange-labs#10]
As we don't care if the template code changes. We should integrate the template code into our git repo and enable commits on it.

**Comment by brtknr** [comment]
Hmm, I think its better to keep track of individual changes to the templates.

**Comment by brtknr** [comment]
And have the flexibility of changing template!

**Comment by px3l** [comment]
I am happier to not change template and build on this than get into the horror that submodules seem to be giving me...

**Comment by px3l** [comment]
Also you can change template very easily by putting the new template in the themes dir and editing config.toml
