### ISSUE TITLE
Host on github pages (for now)

### ISSUE THREAD

**Issue by px3l** [strange-labs-uk/strange-labs#2]
As per these instructions https://gohugo.io/hosting-and-deployment/hosting-on-github/

I keep getting
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:strange-labs-uk/strange-labs-uk.github.io.git' into submodule path 'public' failed
```
which i don't understand as its a public repo...

**Comment by nuxibyte** [comment]
Have you got 2fa on?

**Comment by nuxibyte** [comment]
Have you tried using http url for the repo?

**Comment by brtknr** [comment]
This is not an issue for me, I can clone the repo as submodule with the command:

`git submodule add -b master git@github.com <mailto:git@github.com>:strange-labs-uk/strange-labs-uk.github.io.git public`

**Comment by px3l** [comment]
ok for some reason i tried it again and it worked... only issue now is its not also linking the theme

**Comment by brtknr** [comment]
Check that your ssh key is correctly registered on GitHub. You might need to delete your previous github.com ssh key from ~/.ssh/known_hosts and get a new one.

**Comment by nuxibyte** [comment]
Works for me.

git clone https://github.com/strange-labs-uk/strange-labs-uk.github.io.git <https://github.com/strange-labs-uk/strange-labs-uk.github.io.git>

cd strange-labs-uk.github.io <http://strange-labs-uk.github.io/>

git submodule add -b master git@github.com:strange-labs-uk/strange-labs-uk.github.io.git


errol@malooba.com | +44 7979 472 663 | @malooba

**Comment by px3l** [comment]
whoops lol, wrong button. ok its up now. The theme isn't there however, I have been using `git submodule add` too

**Comment by px3l** [comment]
ok i cannot get the theme to work... no errors in deploying. I added in the -t tag and theme name...
